name: bigdata
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - joblib
  - matplotlib
  - pip
  - pip:
    - bottleneck
    - numexpr
    - python-dateutil
    - pytz
    - six
    - threadpoolctl
    - tzdata